export { default as CoachesDrillForm } from './coachesComponents/CoachesDrillForm';
export { default as CoachesDrillsComp } from './coachesComponents/CoachesDrillsComp';
export { default as CoachesPracticeForm } from './coachesComponents/CoachesPractForm';
// export { default as CoachesPracticeComp } from './coachesComponents/CoachesPracticeComp';
export { default as CoachesPracticeDrills } from './coachesComponents/CoachesPracticeDrills';
export { default as CoachesTeamComp } from './coachesComponents/CoachesTeamComp';
export { default as CoachesTeamForm } from './coachesComponents/CoachesTeamForm';
export { default as PlayerDrillsComp } from './playersComponents/PlayerDrillsComp';
export { default as PlayersTeamComp } from './playersComponents/PlayersTeamComp';
export { default as PlayerPracticeDrills } from './playersComponents/PlayersPractDrills';
// export { default as PlayersPracticeComp } from './playersComponents/PlayersPracticeComp';
export { default as MinxMinNavbar } from './Navbar';
